services:
  lift-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lift-app
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://app:secret@mysql:3306/lift_app?serverVersion=8.0
      MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f/messages
      REDIS_URL: redis://redis:6379
    networks:
      - lift_network

  worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: worker
    command: php bin/console messenger:consume async -vv
    volumes:
      - .:/var/www/html
    depends_on:
      lift-app:
        condition: service_started
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://app:secret@mysql:3306/lift_app?serverVersion=8.0
      MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f/messages
      REDIS_URL: redis://redis:6379
    restart: unless-stopped
    networks:
      - lift_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lift-app
    networks:
      - lift_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lift_app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - lift_network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - lift_network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - lift_network

volumes:
  mysql_data:

networks:
  lift_network:
    driver: bridge
